### ISSUE TITLE
None for config key: DATASETS

### ISSUE THREAD

**Issue by anlimo1510** [shenyunhang/DRN-WSOD-pytorch#3]
Hi Shenyun, thanks for sharing the codes. 

I got an error when trying to train a PCL ResNet 101 WS by the command 
```
python3 projects/WSL/tools/train_net.py --num-gpus 4 --config-file projects/WSL/configs/PascalVOC-Detection/pcl_WSR_101_DC5_1x.yaml OUTPUT_DIR output/pcl_WSR_101_DC5_VOC07_`date +'%Y-%m-%d_%H-%M-%S'`
```

The error message is shown below:

```
Traceback (most recent call last):
  File "tools/train_net.py", line 255, in <module>
    args=(args,),
  File "/home/xx/envs/detectron2/lib/python3.6/site-packages/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "tools/train_net.py", line 218, in main
    cfg = setup(args)
  File "tools/train_net.py", line 210, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/xx/envs/detectron2/lib/python3.6/site-packages/detectron2/config/config.py", line 49, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/xx/envs/detectron2/lib/python3.6/site-packages/fvcore/common/config.py", line 120, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/xx/envs/detectron2/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/xx/envs/detectron2/lib/python3.6/site-packages/yacs/config.py", line 474, in _merge_a_into_b
    v = _check_and_coerce_cfg_value_type(v, b[k], k, full_key)
  File "/home/xx/envs/detectron2/lib/python3.6/site-packages/yacs/config.py", line 537, in _check_and_coerce_cfg_value_type
    original_type, replacement_type, original, replacement, full_key
ValueError: Type mismatch (<class 'detectron2.config.config.CfgNode'> vs. <class 'NoneType'>) with values (PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
PROPOSAL_FILES_TEST: ()
PROPOSAL_FILES_TRAIN: ()
PROPOSAL_FILES_VAL: ()
TEST: ()
TRAIN: ()
VAL: () vs. None) for config key: DATASETS
```

Seems that it fails to follow the base setting for DATASETS in `Base-RCNN-DilatedC5.yaml`

**Comment by shenyunhang** [comment]
Thanks for pointing out.
We have fixed it.

**Comment by anlimo1510** [comment]
thank you
